apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: master
      port: {{ .Values.service.ports.http }}
      targetPort: {{ .Values.service.ports.http }}
    - name: slave
      port: {{ .Values.service.ports.jnlp }}
      targetPort: {{ .Values.service.ports.jnlp }}
  selector:
    app: {{ .Values.service.name }}
